version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./logs/weasyprint.log:/code/logs/weasyprint.log
    ports:
      - 8000:8000
